name: CI 🚀

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          registry-url: https://npm.pkg.github.com
          cache: "pnpm"
      - uses: actions/cache@v4
        with:
          path: node_modules/**
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node-modules-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Test Components
        run: pnpm test

      - name: Linter
        run: pnpm lint

      - name: Build Project
        run: pnpm build
